name: "test-benchmark"
seed: 42
save_root_dir: "./outputs"
input_modality: "rgb"
save_dir: ???
reconstruction_results_dir: ???
debug: False
pred_mask: False
pred_mask_iou_threshold: 0.5
gt_labels: false
from_existing: false
from_shared_vlm: false
save_shared_vlm: false
disable_vlm_calls: false
vlm_only: false
shared_vlm_root: null
segmentation_results_dir: ???
save_mesh: True

defaults:
  - dataset: dataset

# Options: "rgb+extrinsics+intrinsics", "rgb"

  - vlm_segmentation: gemini_segmentation

  - segmentation: VisionReasoner

  - fusion: feature_matching

  - reconstruction: da3

  - articulation: iTACO

  - vlm_function: gemini_function