name: "Uniform"
root_path: "./full_dataset"
meta_file: "./full_dataset/dataset_metadata.json"
image_type: "cropped"  # can be "undistorted" or "cropped"
sample_strategy: "fix_step"  # can be "fix_size" or "fix_step"
sample_num: 1  # number of sample when sample_strategy is "fix_size", number of sample interval when sample_strategy is "fix_step"