name: "Uniform"
root_path: "./full_dataset"
meta_file: "./full_dataset/dataset_new_metadata5.json"
image_type: "undistorted"  # can be "undistorted" or "cropped"
sample_strategy: "fix_size"  # can be "fix_size" or "all"
sample_num: 20  # used when sample_strategy is "fix_size"