model: "SAM3Agent"
reasoning_model_path: null
segmentation_model_path: "facebook/sam3"
device: "cuda"
use_gt_depth: false
save_results: true
max_query: 1
frame_subsample: 20
disable_vlm_judge: false
propagate_with_sam3: true
save_visualizations: false
sam3_propagation:
  device: "cuda"
  checkpoint_path: null
  bpe_path: null
  offload_video_to_cpu: false
sam3:
  llm_server_url: "http://0.0.0.0:8001/v1"
  llm_model: "Qwen/Qwen3-VL-8B-Thinking"
  llm_api_key: ""
  confidence_threshold: 0.5
  max_generations: 10
  output_dir: "sam3_agent_out"
vlm_judge:
  role: "segmentation_judge"
  vlm_model: "gemini-2.5-flash"
  prompt_template: "Here are two images. The first image is the original image. I do segmentation on the first image, based on this text description: {PartDescription}. The result is shown in the second image, marked in green. Do you think the segmentation result in the second image is accurate or not. Please answer in this template: <answer>xxx</answer> <reason>yyy</reason> Substitute \"xxx\" with 'yes' or 'no' and \"yyy\" with the reason of your answer. DO NOT answer any other information."
  max_query: 3
